### PR TITLE
support to save model into binary files

### PR DESCRIPTION
**Pull request by embbnux**
As localStorageIO, fileStorageIO saves model into files.

**Advantages**:
fileStorageIO save weight with binary which is smaller than base64 string in localStorageIO.

Support to save about 10MB weight binary.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-wechat/50)

### CODE REVIEW

**Comment by embbnux** [comment]
@googlebot I signed it!

**Comment by embbnux** [comment]
Thanks @pyu10055 will add them

**Comment by embbnux** [comment]
thanks @pyu10055 , updated. 
`getModelPaths` can't refactor with `getModelKeys` in local_storage, as they are different in key and value.

**Comment by embbnux** [comment]
Thanks @pyu10055 , will fix them soon

**Comment by embbnux** [comment]
Hi @pyu10055 Fixed. For `resolve` in `wx.unlink` fail, just want to ignore the error when remove file fail (file not exist)

**Comment by pyu10055** [comment]
@embbnux I tried your changes, seems getFileSystemManager API is not available in the plugin scope, it works inside the user program. Have you tried with local plugin development? Thanks

**Comment by embbnux** [comment]
@pyu10055 Sorry, I only tested it in min-program's project. Just checked the plugin api, it doesn't support `wx.getFileSystemManager` API now. 
We need to update docs, and recommend developer to require this file in their project.

**Comment by ifunplus** [comment]
when I use fileStorageIO or localStorage  to cache models, an error occurs: mkdir:fail permission denied.  suspect weixin has limited a custom path to save file. somebody knows how to do to solve the problem

**Pull request merged**
